Nama_lengkap = input("Nama lengkap: ")
Nama_panggilan = input("Nama panggilan: ")
Tempat_lahir = input("Tempat lahir: ")
Tanggal_lahir = input("Tanggal lahir: ")
Umur_dalam_tahun = int(input("Umur dalam tahun: "))
umur_dalam_bulan = 12*Umur_dalam_tahun
print("umur dalam bulan : ", umur_dalam_bulan)
umur_dalam_hari = 365*12*Umur_dalam_tahun
print("umur dalam hari : ", umur_dalam_hari)
Size_sepatu = int(input("Ukuran sepatu: "))
Alamat = input("Alamat rumah: ")
Jurusan = input("Jurusan: ")
Tinggi_badan = float(input("Tinggi badan : "))
Berat_badan = float(input("Berat badan : "))
BMI = Berat_badan*100 / (Tinggi_badan * Tinggi_badan)
print("BMI : ", BMI)
Nama_ayah = input("Nama ayah: ")
Nama_ibu = input("Nama ibu : ")
Jumlah_saudara = int(input("Jumlah saudara: "))
Asal_SMA = input("Asal SMA: ")
Makanan_Kesukaan = input("Makanan Kesukaan: ")
Minuman_Kesukaan = input("Minuman Kesukaan: ")
Hobi = input("Hobi: ")
Uang_jajan_perbulan = float(input("Uang jajan perbulan: "))
Uang_jajan_perminggu = Uang_jajan_perbulan / 4
print("Uang jajan perbulan: ", Uang_jajan_perminggu)
Uang_jajan_perhari = Uang_jajan_perbulan / 30
print("Uang jajan perhari: ", Uang_jajan_perhari)
Cita_cita = input("Cita-cita: ")
Tempat_Impian = input("Tempat impian: ")
Barang_kesukaan = input("Barang kesukaan: ")
Barang_yang_diinginkan = input("Barang yang diinginkan: ")
Barang_yang_dibutuhkan = input("Barang yang dibutuhkan: ")
Film_kesukaan = input("Film kesukaan: ")
Lagu_kesukaan = input("Lagu kesukaan: ")